stages:
  - mavenbuild
  - maventest
  - autodeploy
  
maven-build:
    stage: mavenbuild
    tags:
      - BACKEND
    script:
      - cd Backend/309Backend
      - mvn package -B

maven-test:
    stage: maventest
    tags:
      - BACKEND
    script:
      - cd Backend/309Backend
      - mvn test
      - mvn package -B
    artifacts:
      paths:
        - Backend/309Backend/target/*.jar

autoDeploy:
  stage: autodeploy
  tags: 
    - BACKEND
  script: 
    - cd Backend/309Backend
    - mvn test
    - mvn package -B
    - sudo mv target/*.jar /target/web-demo.jar
    - sudo systemctl stop system-web-demo
    - sudo systemctl start system-web-demo